apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: staging-eks-cluster
spec:
  forProvider:
    region: us-east-1
    resourceVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      providerConfigRef:
        name: aws-provider
      roleArnRef: {}
      securityGroupIdRefs:
        - name:
            - staging-eks-security-group
      subnetIdRefs:
        - {}
      version: "1.21"
      writeConnectionSecretToRef:
        name: staging-eks-connection-secret
        namespace: staging
