apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: crossplane-eks-cluster
spec:
  forProvider:
    region: us-east-1
    resourceVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      providerConfigRef:
        name: aws-provider
      roleArnRef: {}
      securityGroupIdRefs:
        - name:
            - crossplane-eks-cluster-sg
      subnetIdRefs:
        - {}
      version: "1.21"
      writeConnectionSecretToRef:
        name: crossplane-eks-cluster-connection-secret
        namespace: default
