apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: crossplane-aks-cluster
spec:
  disableRBAC: false
  dnsNamePrefix: crossplane-aks-cluster
  location: eastus
  nodeCount: 3
  nodeVMSize: Standard_D2_v2
  providerConfigRef:
    name: azure-provider
  resourceGroupNameRef:
    name: crossplane-aks-cluster-rg
  version: 1.18.14
  vnetSubnetID:
    name: crossplane-aks-cluster-subnet
  vnetSubnetIDRef:
    name: crossplane-aks-cluster-subnet
  writeConnectionSecretToRef:
    name: crossplane-aks-cluster-connection-secret
    namespace: default
