apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications-bot
    app.kubernetes.io/version: v1.2.1
    helm.sh/chart: argocd-notifications-1.8.1
  name: argocd-notifications-bot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: v1.2.1
    helm.sh/chart: argocd-notifications-1.8.1
  name: argocd-notifications-controller
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: v1.2.1
    helm.sh/chart: argocd-notifications-1.8.1
  name: argocd-notifications-secret
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: v1.2.1
    helm.sh/chart: argocd-notifications-1.8.1
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: 
  service.slack: |
    token: $slack-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: v1.2.1
    helm.sh/chart: argocd-notifications-1.8.1
  name: argocd-notifications-controller
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - argocd-notifications-cm
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - argocd-notifications-secret
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: v1.2.1
    helm.sh/chart: argocd-notifications-1.8.1
  name: argocd-notifications-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-notifications-controller
subjects:
  - kind: ServiceAccount
    name: argocd-notifications-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: v1.2.1
    helm.sh/chart: argocd-notifications-1.8.1
  name: argocd-notifications-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd-notifications
      app.kubernetes.io/name: argocd-notifications
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: argocd-notifications
        app.kubernetes.io/name: argocd-notifications
    spec:
      containers:
        - command:
            - /app/argocd-notifications-backend
            - controller
            - --loglevel=info
            - --secret-name=argocd-notifications-secret
            - --config-map-name=argocd-notifications-cm
          image: argoprojlabs/argocd-notifications:v1.2.1
          imagePullPolicy: IfNotPresent
          name: argocd-notifications-controller
          resources: {}
          workingDir: /app
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argocd-notifications-controller
