export const HelmChartFeatureFlags: any = {
  argo_cd: true,
  argo_image_updater: true,
  argo_notifications: true,
  argo_rollouts: true,
  argo_workflows: true,
  cert_manager: true,
  cluster_autoscaler: true,
  consul: true,
  crossplane: true,
  kube_state_metrics: true,
  metrics_server: true,
  kube_prometheus_stack: true,
  secrets_store_csi_driver: true,
  tekton_pipeline: true,
  vault: true,
};
