export const HelmChartFeatureFlags: any = {
  argo_cd: true,
  argo_image_updater: true,
  argo_notifications: true,
  argo_rollouts: true,
  argo_workflows: true,
  cert_manager: true,
  cluster_autoscaler: true,
  consul: true,
  crossplane: true,
  kube_state_metrics: true,
  metrics_server: true,
  kube_prometheus_stack: true,
  vault_secrets_store_csi_driver: true,
  tekton_pipeline: true,
  vault: true,
  aws_ebs_csi_driver: false,
  aws_efs_csi_driver: false,
  aws_fsx_csi_driver: false,
  aws_secret_store_csi_driver: false,
  aws_cloudwatch_agent: false,
  aws_load_balancer_controller: false,
};
