name: CDKTF Diff

on:
  pull_request:
    branches:
      - master

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  stack: staging

jobs:
  build:
    name: "Terraform CDK plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"

      - name: Install CDKTF CLI v0.17.0
        run: npm install -g cdktf-cli@0.17.0

      - name: Install Terraform v1.5.3
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Install dependencies
        run: yarn install

      - name: Set Terraform Token
        run: |
          mkdir -p ~/.terraform.d
          echo '{
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_API_TOKEN }}"
              }
            }
          }' > ~/.terraform.d/credentials.tfrc.json

#      - name: deploy
#        run: cdktf deploy ${{ env.stack }} --auto-approve
